### ISSUE TITLE
TileEntity拼写错误

### ISSUE THREAD

**Issue by umaron** [FledgeXu/Neutrino#4]
[https://github.com/FledgeXu/Neutrino/blob/master/src/tileentity/firsttileentity.md](url)

> 这里的构造方法，我们向我们的父类传入了一个TilEnttityType，那么这个TilEntityType又是什么东西呢？

不只这两个，在这篇里面这个单词拼错了很多次...

**Comment by umaron** [comment]
顺便提一点建议...

> 我们在这里加入了markDirty()方法，这个方法的意思是标记了我们数据被修改，让游戏知道在关闭的时候要保存调用保存方法。这样做是因为相对于CPU的执行速度，硬盘的保存和读写速度是非常慢的，所以如果频繁的进行保存和读写操作会严重拖慢游戏的速度，一个合理的方法就是标记我们需要保存的数据，然后在一个统一的时间点一起保存，markDirty()的作用正是如此。

这部分，容易让人误解（我是误解了），以为不调用的时候会导致一直读写。我上官方文档看了才发现的，而且官方文档用的也还是markDirty()。我1.16.5-36.1.0mdk，映射默认是

> mappings channel: 'official', version: '1.16.5'

ForgeGradle版本是4.1.+的，好多方法名都变了(真的多，像这一篇里面的isRemote,read,write,sendStatusMessage等等还没列完.....)，这也是我跑去看官方文档的原因，但是官方文档的也还没改过来...按照官方文档说明的作用和方法名才在源码里找到markDirty被改成了setChanged

**Comment by FledgeXu** [comment]
我对Minecraft开发目前没什么兴趣……

**Comment by umaron** [comment]
好吧...pr完才发现我应该在boson提issue的...从那边点源代码再点到个人首页，看到这个就点进来了...
